// Original deterministic viewer fixture. Not an agent-generated design benchmark.
import rhino3dm from 'rhino3dm';
import {writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const r=await rhino3dm(),doc=new r.File3dm();doc.settings().modelUnitSystem=r.UnitSystem.Meters;
doc.applicationName='Architecture Agent viewer fixture';
const layers=[['Structure','#e0dbcb'],['Glazing','#94aea8'],['Screens','#a77c53'],['Landscape','#a5ae8c'],['Terraces','#c9c6b6']];
for(const [name,hex]of layers){const l=new r.Layer();l.name=name;l.color={r:parseInt(hex.slice(1,3),16),g:parseInt(hex.slice(3,5),16),b:parseInt(hex.slice(5,7),16),a:255};doc.layers().add(l);l.delete();}
const glass=new r.Material();glass.name='Glass';glass.diffuseColor={r:127,g:165,b:163,a:255};glass.transparency=.42;doc.materials().add(glass);
let total=0;
function box(name,x,y,z,w,d,h,layer=0,brep=false){
 const m=new r.Mesh(),v=[[x,y,z],[x+w,y,z],[x+w,y+d,z],[x,y+d,z],[x,y,z+h],[x+w,y,z+h],[x+w,y+d,z+h],[x,y+d,z+h]];
 const faces=[[0,2,1],[0,3,2],[4,5,6],[4,6,7],[0,1,5],[0,5,4],[1,2,6],[1,6,5],[2,3,7],[2,7,6],[3,0,4],[3,4,7]];
 for(const p of v)m.vertices().add(...p);for(const f of faces)m.faces().addTriFace(...f);
 assert.equal(m.isClosed,true);for(const f of faces){const p=v[f[0]],u=v[f[1]].map((a,i)=>a-p[i]),t=v[f[2]].map((a,i)=>a-p[i]);const normal=[u[1]*t[2]-u[2]*t[1],u[2]*t[0]-u[0]*t[2],u[0]*t[1]-u[1]*t[0]],c=[x+w/2,y+d/2,z+h/2];assert(normal.reduce((sum,n,i)=>sum+n*(p[i]-c[i]),0)>0);}
 const a=new r.ObjectAttributes();a.name=name;a.layerIndex=layer;a.setUserString('fixture','original-viewer-study');if(layer===1){a.materialSource=r.ObjectMaterialSource.MaterialFromObject;a.materialIndex=0;}
 if(brep){const b=r.Brep.createFromMesh(m,true);assert.equal(b.faces().count,12);for(let i=0;i<12;i++){const mesh=new r.Mesh();for(const vi of faces[i])mesh.vertices().add(...v[vi]);mesh.faces().addTriFace(0,1,2);const face=b.faces().get(i);assert(face.setMesh(mesh,r.MeshType.Render));face.delete();mesh.delete();}doc.objects().addBrep(b,a);b.delete();}else doc.objects().addMesh(m,a);a.delete();m.delete();total++;
}
box('Site terrace',-12,-9,-.45,24,18,.35,4,true);
for(const z of [0,3.6,7.2]){
 box(`West slab ${z}`,-10,-7,z,5,14,.26);box(`East slab ${z}`,5,-7,z,5,14,.26);box(`North slab ${z}`,-5,3,z,10,4,.26);box(`South slab ${z}`,-5,-7,z,10,3,.26);
}
for(const x of [-9.8,-5.2,5,9.6])for(const y of [-6.8,-2.4,2.2,6.5])box('Concrete column',x,y,.26,.22,.22,6.94);
for(const z of [.27,3.87]){
 for(const x of [-9.85,9.75])box('Outer glazing',x,-6.75,z,.08,13.4,3.3,1);
 for(const x of [-5.15,5.05])box('Courtyard glazing',x,-4,z,.08,7,3.3,1);
 box('North glazing',-9.6,6.72,z,19.2,.08,3.3,1);
 box('South glazing west',-9.6,-6.84,z,7.5,.08,3.3,1);
 box('South glazing east',2,-6.84,z,7.6,.08,3.3,1);
 box('Service core',6,2.6,z,2.8,3.6,3.25,0);
}
for(let i=0;i<45;i++){box('Timber west screen',-10.04,-6.8+i*.3,.4,.15,.07,6.75,2);box('Timber east screen',9.92,-6.8+i*.3,.4,.15,.07,6.75,2);}
for(let i=0;i<9;i++)box('Entry stair',-1.9,-8.65+i*.18,-.3+i*.045,3.8,.19,.05,4);
box('Courtyard garden',-4.55,-3.5,.03,9.1,5.9,.19,3);box('Garden seat',-3.7,1.9,.28,5.7,.45,.4,2);
box('Gallery stair landing',-4.7,3.3,1.85,2.8,1.1,.18,0);
for(let i=0;i<20;i++)box('Gallery stair tread',-4.7,3.3-i*.285,.26+i*.18,1.3,.29,.18,0);
await mkdir('fixtures',{recursive:true});await writeFile('fixtures/courtyard-study.3dm',doc.toByteArray());
await writeFile('fixtures/README.md',`Original courtyard study for viewer QA, generated by tests/make_fixture.mjs. ${total} named geometry objects; 5 layers; meters, Z-up. One actual BRep with 12 stored render meshes; remaining objects are closed triangle meshes. This is a UI fixture, not an LLM output or native Rhino execution. No third-party reference assets.\n`);
console.log(`Wrote real 3dm archive with ${total} objects.`);doc.delete();
