import * as THREE from './vendor/three.module.js';
import {orthographicHeight,perspectiveDistance,sectionCoordinate,modelClipRange} from './camera-math.mjs';
import {buildSceneModel,visibleWorldBounds,deliveryActions} from './model-state.mjs';
import {mountActivityPanel} from './activity.mjs';
import {validatePairedPreview} from './preview.mjs';
const $=id=>document.getElementById(id), stage=$('stage'),canvas=$('canvas');
const token=new URLSearchParams(location.hash.slice(1)).get('token')||'';
let meta=null,model=null,loadedData=null,worker=null,selection=null,localFile=null,loadSerial=0;
let edgesVisible=true,sectionOn=false,axis='z',flipped=false,projection='perspective';
let radius=25,theta=.72,elevation=.5,orthoHeight=30,target=new THREE.Vector3(),bounds=new THREE.Box3();
const fov=38,scene=new THREE.Scene();scene.background=new THREE.Color('#ebece5');
let renderer,renderError=null;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true});}
catch(e){renderError='WebGL is unavailable. Download or open the original file in Rhino, or enable browser graphics acceleration for preview.';}
if(renderer){renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.localClippingEnabled=true;renderer.outputEncoding=THREE.sRGBEncoding;}
const perspective=new THREE.PerspectiveCamera(fov,1,.01,1000000),ortho=new THREE.OrthographicCamera(-15,15,15,-15,.01,1000000);let camera=perspective;
camera.up.set(0,0,1);ortho.up.set(0,0,1);
scene.add(new THREE.AmbientLight(0xffffff,.66));
const sun=new THREE.DirectionalLight(0xffffff,.6);sun.position.set(-20,-30,60);scene.add(sun);
const fill=new THREE.DirectionalLight(0xdde8ee,.18);fill.position.set(30,20,15);scene.add(fill);
const clip=new THREE.Plane(new THREE.Vector3(0,0,-1),0),ray=new THREE.Raycaster(),pointer=new THREE.Vector2();
let grid=null,pickables=[],selectionBox=null,toastTimer;
function toast(message,sticky=false){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);if(!sticky)toastTimer=setTimeout(()=>$('toast').hidden=true,6500);}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'X-Viewer-Token':token,...options.headers}});if(!response.ok){let message='Viewer service request failed';try{message=(await response.json()).error||message;}catch{}throw new Error(message);}return response;}
mountActivityPanel({panel:$('activity'),list:$('activity-events'),title:$('activity-title'),notice:$('activity-notice'),api,document,window});
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer?.setSize(w,h,false);perspective.aspect=w/h;perspective.updateProjectionMatrix();ortho.top=orthoHeight/2;ortho.bottom=-orthoHeight/2;ortho.left=-orthoHeight*w/h/2;ortho.right=-ortho.left;ortho.updateProjectionMatrix();}
function updateCamera(){camera.position.set(target.x+radius*Math.cos(elevation)*Math.sin(theta),target.y-radius*Math.cos(elevation)*Math.cos(theta),target.z+radius*Math.sin(elevation));camera.lookAt(target);if(!bounds.isEmpty()){const range=modelClipRange(bounds.getSize(new THREE.Vector3()).length(),camera.position.distanceTo(bounds.getCenter(new THREE.Vector3())));camera.near=range.near;camera.far=range.far;camera.updateProjectionMatrix();}camera.updateMatrixWorld();}
function setProjection(next){if(next===projection)return;const distance=camera.position.distanceTo(target);if(next==='axon'){orthoHeight=orthographicHeight(distance,fov);camera=ortho;}else{radius=perspectiveDistance(orthoHeight,fov);camera=perspective;}projection=next;for(const [id,mode]of [['perspective','perspective'],['axon','axon']]){$(id).classList.toggle('active',mode===next);$(id).setAttribute('aria-pressed',String(mode===next));}$('projection-label').textContent=next==='axon'?'AXONOMETRIC':'PERSPECTIVE';resize();updateCamera();}
function fit(){if(!model||bounds.isEmpty())return;const size=bounds.getSize(new THREE.Vector3());target.copy(bounds.getCenter(new THREE.Vector3()));const sphere=bounds.getBoundingSphere(new THREE.Sphere());const aspect=stage.clientWidth/stage.clientHeight;const angle=Math.min(fov*Math.PI/360,Math.atan(Math.tan(fov*Math.PI/360)*aspect));radius=sphere.radius/Math.sin(angle)*1.08;orthoHeight=orthographicHeight(radius,fov);for(const c of [perspective,ortho]){c.near=Math.max(size.length()/10000,.00001);c.far=Math.max(size.length()*1000,100);c.updateProjectionMatrix();}resize();updateCamera();}
function updateSection(){const empty=bounds.isEmpty();$('cut').disabled=empty;const v=empty?0:sectionCoordinate(bounds.min[axis],bounds.max[axis],Number($('cut').value));clip.normal.set(0,0,0);clip.normal[axis]=flipped?1:-1;clip.constant=flipped?-v:v;$('cut-value').textContent=empty?'No visible geometry':`${axis.toUpperCase()} ${v.toFixed(2)} ${loadedData?.units||''}`;model?.traverse(o=>{if(o.material){for(const m of [].concat(o.material)){m.clippingPlanes=sectionOn&&!empty?[clip]:[];m.clipShadows=true;m.needsUpdate=true;}}});$('cut-label').hidden=!sectionOn;}
function setSection(on){sectionOn=on;$('section-panel').hidden=!on;$('section-toggle').classList.toggle('active',on);$('section-toggle').setAttribute('aria-pressed',String(on));updateSection();}
function clearSelection(){selection=null;$('selection').textContent='Click an element to inspect it';if(selectionBox){scene.remove(selectionBox);selectionBox.geometry.dispose();selectionBox.material.dispose();selectionBox=null;}}
function select(object){clearSelection();selection=object;const row=object.userData.record,layer=loadedData.layers.find(l=>l.index===row.layer);$('selection').replaceChildren();const strong=document.createElement('b');strong.textContent=row.name;$('selection').append(strong,document.createElement('br'),`${row.kind} · ${layer?.name||'Default'}`,document.createElement('br'));const small=document.createElement('small');small.textContent=row.id;$('selection').append(small);selectionBox=new THREE.BoxHelper(object,0xc57b53);scene.add(selectionBox);}
function disposeModel(){clearSelection();if(model){scene.remove(model);const geometries=new Set(),materials=new Set();model.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)[].concat(o.material).forEach(m=>materials.add(m));});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}if(grid){scene.remove(grid);grid.geometry.dispose();[].concat(grid.material).forEach(m=>m.dispose());}grid=null;model=null;pickables=[];bounds.makeEmpty();}
function showWarnings(warnings){$('warnings').hidden=!warnings.length;$('warning-summary').textContent=`${warnings.length} model note${warnings.length===1?'':'s'}`;$('warning-list').replaceChildren();warnings.slice(0,100).forEach(w=>{const li=document.createElement('li');li.textContent=w;$('warning-list').append(li);});}
function refreshVisibleBounds(){
 bounds.copy(visibleWorldBounds(model,THREE));
 if(bounds.isEmpty()){$('model-size').textContent='No visible geometry';if(grid)grid.visible=false;updateSection();return;}
 const size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());
 if(!grid){grid=new THREE.GridHelper(1,32,0xc5cbbd,0xd5dacd);grid.rotation.x=Math.PI/2;grid.material.transparent=true;grid.material.opacity=.5;scene.add(grid);}
 const extent=Math.max(size.x,size.y,.001)*2.5;grid.visible=true;grid.scale.setScalar(extent);grid.position.set(center.x,center.y,bounds.min.z-.015*size.length());
 $('model-size').textContent=`${size.x.toFixed(1)} × ${size.y.toFixed(1)} × ${size.z.toFixed(1)} · ${loadedData.units} · Z-up · visible`;
 // Refresh limits without moving the camera or changing its zoom/target.
 for(const c of [perspective,ortho]){c.far=Math.max(c.far,c.position.distanceTo(center)+size.length()*10,100);c.updateProjectionMatrix();}
 updateSection();
}
function updateDeliveryControls(){const actions=deliveryActions(meta,localFile);$('download').disabled=!actions.download;$('open-rhino').disabled=!actions.rhino;$('open-gh').disabled=!actions.grasshopper;}
function createModel(data){
 if(renderError)throw new Error(renderError);
 disposeModel();loadedData=data;const built=buildSceneModel(data,THREE,edgesVisible);model=built.model;pickables=built.pickables;scene.add(model);
 if(!pickables.length){showWarnings(built.warnings);throw new Error('No displayable geometry found. Download or open the original model in Rhino to generate render meshes.');}
 $('layers').replaceChildren();
 for(const layer of data.layers){
  const objects=[];model.traverse(o=>{if(o.userData.record?.layer===layer.index)objects.push(o);});if(!objects.length)continue;
  const label=document.createElement('label');label.className='layer';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=layer.visible!==false;
  const swatch=document.createElement('span');swatch.className='swatch';swatch.style.background=`rgb(${layer.color.r},${layer.color.g},${layer.color.b})`;
  const name=document.createElement('span');name.className='layer-name';name.textContent=layer.name;const count=document.createElement('small');count.textContent=objects.length;
  label.append(checkbox,swatch,name,count);checkbox.addEventListener('change',()=>{objects.forEach(o=>o.visible=checkbox.checked&&o.userData.record.visible!==false);clearSelection();refreshVisibleBounds();});$('layers').append(label);
 }
 let triangles=0;model.traverse(o=>{if(o.isMesh)triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;});$('counts').textContent=`${pickables.length} display objects · ${Math.round(triangles).toLocaleString()} triangles`;$('filedetail').textContent=`${data.sourceCount} source objects · ${data.layers.length} layers`;
 $('welcome').hidden=true;theta=.72;elevation=.53;refreshVisibleBounds();fit();showWarnings(built.warnings);
}
async function load(bytes,name,local=false){const serial=++loadSerial;worker?.terminate();disposeModel();loadedData=null;$('layers').replaceChildren();$('warnings').hidden=true;$('welcome').hidden=true;$('counts').textContent='Reading model';$('filedetail').textContent='Loading…';$('loading').hidden=false;$('filename').textContent=name;localFile=local?new Blob([bytes],{type:'application/octet-stream'}):null;updateDeliveryControls();const decoder=new Worker('./decode-worker.js');worker=decoder;try{const data=await new Promise((resolve,reject)=>{const deadline=setTimeout(()=>{decoder.terminate();reject(new Error('Model decoding exceeded 60 seconds. Try a smaller file with embedded render meshes.'));},60000);decoder.onmessage=e=>{clearTimeout(deadline);e.data.ok?resolve(e.data.result):reject(new Error(e.data.error));};decoder.onerror=e=>{clearTimeout(deadline);reject(new Error(e.message));};decoder.postMessage(bytes,[bytes]);});if(serial!==loadSerial)return;createModel(data);if(local){$('title').textContent=name.replace(/\.3dm$/i,'');$('subtitle').textContent='Imported locally · display geometry from your .3dm';}updateDeliveryControls();}
 catch(e){if(serial===loadSerial){toast(e.message,true);$('welcome').hidden=false;$('filedetail').textContent='Preview unavailable';$('counts').textContent='No model displayed';updateDeliveryControls();}}finally{if(serial===loadSerial){$('loading').hidden=true;decoder.terminate();worker=null;}}}
async function loadPreview(artifact){
 const serial=++loadSerial;worker?.terminate();disposeModel();loadedData=null;localFile=null;
 $('layers').replaceChildren();$('warnings').hidden=true;$('welcome').hidden=true;
 $('counts').textContent='Reading paired preview';$('loading').hidden=false;$('filename').textContent=artifact.filename;updateDeliveryControls();
 try{const data=validatePairedPreview(await(await api(meta.preview.url)).json(),meta.preview,artifact);
  if(serial!==loadSerial)return;createModel(data);
  $('subtitle').textContent='Preview generated from the same profiles and dimensions · Download preserves the native Rhino solids';
  $('filedetail').textContent=`${data.sourceCount} native objects · ${data.layers.length} layers · paired mesh preview`;
 }catch(e){if(serial===loadSerial){toast(e.message,true);$('welcome').hidden=false;$('filedetail').textContent='Paired preview unavailable';$('counts').textContent='No model displayed';}}
 finally{if(serial===loadSerial){$('loading').hidden=true;updateDeliveryControls();}}
}
async function importFile(file){if(!file)return;if(!/\.3dm$/i.test(file.name)){toast('Choose a Rhino .3dm file.');return;}if(file.size>256*1024*1024){toast('This preview accepts .3dm files up to 256 MB.');return;}await load(await file.arrayBuffer(),file.name,true);}
async function openArtifact(kind){const artifact=meta?.artifacts.find(a=>a.kind===kind);if(!artifact)return;try{await api('/api/open',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({artifact_id:artifact.id})});toast(kind==='gh'?'Grasshopper file sent to Rhino.':'Model sent to Rhino.');}catch(e){toast(e.message);}}
async function download(){let url,revoke=false,name=localFile?$('filename').textContent:meta?.artifacts.find(a=>a.kind==='3dm')?.filename;if(localFile){url=URL.createObjectURL(localFile);revoke=true;}else{const artifact=meta?.artifacts.find(a=>a.kind==='3dm');if(!artifact)return;const response=await api(artifact.url);url=URL.createObjectURL(await response.blob());revoke=true;}const a=document.createElement('a');a.href=url;a.download=name;a.click();if(revoke)setTimeout(()=>URL.revokeObjectURL(url),1000);}
// Orbit, pan and zoom operate in Rhino's native Z-up world frame.
let gesture=null;
canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);gesture={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,pan:e.shiftKey||e.button!==0};});
canvas.addEventListener('pointermove',e=>{if(!gesture)return;const dx=e.clientX-gesture.x,dy=e.clientY-gesture.y;if(gesture.pan){const h=projection==='axon'?orthoHeight:orthographicHeight(radius,fov),scale=h/stage.clientHeight;const right=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,0),up=new THREE.Vector3().setFromMatrixColumn(camera.matrixWorld,1);target.addScaledVector(right,-dx*scale).addScaledVector(up,dy*scale);}else{theta-=dx*.005;elevation=Math.max(-Math.PI/2+.003,Math.min(Math.PI/2-.003,elevation+dy*.005));}gesture.x=e.clientX;gesture.y=e.clientY;updateCamera();});
canvas.addEventListener('pointerup',e=>{if(gesture&&Math.hypot(e.clientX-gesture.startX,e.clientY-gesture.startY)<4&&!gesture.pan){const rect=canvas.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(pickables,false).filter(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent;}return !sectionOn||clip.distanceToPoint(h.point)>=0;});if(hits[0])select(hits[0].object);else clearSelection();}gesture=null;});canvas.addEventListener('pointercancel',()=>gesture=null);
canvas.addEventListener('wheel',e=>{e.preventDefault();const factor=Math.exp(Math.max(-100,Math.min(100,e.deltaY))*.002);const size=Math.max(bounds.getSize(new THREE.Vector3()).length(),1);if(projection==='axon'){orthoHeight=Math.max(size*.001,Math.min(size*100,orthoHeight*factor));resize();}else{radius=Math.max(size*.001,Math.min(size*100,radius*factor));updateCamera();}},{passive:false});
$('perspective').onclick=()=>setProjection('perspective');$('axon').onclick=()=>setProjection('axon');$('fit').onclick=fit;$('top').onclick=()=>{setProjection('axon');theta=0;elevation=Math.PI/2-.003;updateCamera();};$('section-toggle').onclick=()=>setSection(!sectionOn);$('section-close').onclick=()=>setSection(false);$('cut').oninput=updateSection;$('flip').onclick=()=>{flipped=!flipped;updateSection();};document.querySelectorAll('[data-axis]').forEach(b=>b.onclick=()=>{axis=b.dataset.axis;document.querySelectorAll('[data-axis]').forEach(x=>x.classList.toggle('active',x===b));updateSection();});$('edges').onclick=()=>{edgesVisible=!edgesVisible;$('edges').classList.toggle('active',edgesVisible);$('edges').setAttribute('aria-pressed',String(edgesVisible));model?.traverse(o=>{if(o.userData.edge)o.visible=edgesVisible;});};$('show-all').onclick=()=>{$('layers').querySelectorAll('input').forEach(c=>{c.checked=true;c.dispatchEvent(new Event('change'));});};$('import').onclick=$('welcome-import').onclick=()=>$('file').click();$('file').onchange=()=>importFile($('file').files[0]);$('open-rhino').onclick=()=>openArtifact('3dm');$('open-gh').onclick=()=>openArtifact('gh');$('download').onclick=()=>download().catch(e=>toast(e.message));
stage.addEventListener('dragover',e=>{e.preventDefault();stage.classList.add('dragging');});stage.addEventListener('dragleave',e=>{if(!stage.contains(e.relatedTarget))stage.classList.remove('dragging');});stage.addEventListener('drop',e=>{e.preventDefault();stage.classList.remove('dragging');importFile(e.dataTransfer.files[0]);});window.addEventListener('keydown',e=>{if(e.target.tagName==='INPUT')return;if(e.key.toLowerCase()==='f')fit();if(e.key==='Escape'){clearSelection();setSection(false);}});new ResizeObserver(resize).observe(stage);resize();updateCamera();renderer?.setAnimationLoop(()=>renderer.render(scene,camera));
try{meta=await(await api('/api/model')).json();updateDeliveryControls();$('title').textContent=meta.title||'Untitled model';$('subtitle').textContent=meta.subtitle||'Generated architecture · explore, inspect, continue.';const artifact=meta.artifacts.find(a=>a.kind==='3dm');if(artifact){if(meta.preview)await loadPreview(artifact);else{const response=await api(artifact.url);await load(await response.arrayBuffer(),artifact.filename);}}if(!meta.allow_open){$('open-rhino').title=$('open-gh').title='Local application opening is disabled by this viewer session.';}}catch(e){if(token)toast(e.message,true);}
